const ACTIONS = {
    ADD_TO_CART: 'ADD_TO_CART',
    CLEAR_CART: 'CLEAR_CART',
    LOG_USER: 'LOG_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    GET_USER: 'GET_USER',
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_CART: 'GET_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
}

export default ACTIONS;